# 1. Conexion a la Base de Datos
# Soporta variables comunes en entornos de despliegue como Railway/Heroku
server.port=${PORT:8080}
spring.datasource.url=${DB_URL:${JDBC_DATABASE_URL:${DATABASE_URL:jdbc:postgresql://localhost:8185/tutoria_db}}}
spring.datasource.username=${DB_USER:${DB_USERNAME:${PGUSER:postgres}}}
spring.datasource.password=${DB_PASSWORD:${DATABASE_PASSWORD:${PGPASSWORD:fesa8185}}}

# 2. Configuracion de Hibernate y JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Seguridad y JWT
# En la nube debes configurar la variable JWT_SECRET
app.jwt.secret=${JWT_SECRET:SkillVibe_fesa81852027_Secure_JWT_Key_UCC_Pasto_2026_!}
app.jwt.expiration=86400000

# 4. Formato de Logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=INFO

##esta monda es para no dejar el link quemado dentro del security config
app.cors.allowed-origins=${CORS_ORIGINS:http://localhost:5173,https://skillvibe-frontend.vercel.app}