# 1. Conexion a la Base de Datos
# Este truco añade "jdbc:" al inicio de la URL de Railway automáticamente
server.port=${PORT:8080}
spring.datasource.url=jdbc:${DATABASE_URL:postgresql://localhost:8185/tutoria_db}
spring.datasource.username=${PGUSER:postgres}
spring.datasource.password=${PGPASSWORD:fesa8185}


# 2. Configuracion de Hibernate y JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 3. Seguridad y JWT
# En la nube debes configurar la variable JWT_SECRET en el dashboard de Railway
app.jwt.secret=${JWT_SECRET:SkillVibe_fesa81852027_Secure_JWT_Key_UCC_Pasto_2026_!}
app.jwt.expiration=86400000

# 4. Formato de Logs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.web=INFO

# 5. Configuración de CORS
# Se traen desde las variables de entorno o usa los de Vercel/Local por defecto
app.cors.allowed-origins=${CORS_ORIGINS:http://localhost:5173,https://skillvibe-frontend.vercel.app,https://skillvibe-frontend-qhz980mj7-miguelsantacruz1s-projects.vercel.app}